### ISSUE TITLE
Support for heatmaps

### ISSUE THREAD

**Issue by mhourahine** [MaazAli/Meteor-HighCharts#10]
Hi thanks for writing this wrapper!  I'd like to add support for [Heatmaps](http://www.highcharts.com/demo/heatmap).  What's the best way to include that in this package?

**Comment by jhuenges** [comment]
I guess including [heatmaps.js](http://code.highcharts.com/modules/heatmap.js) into [/lib](https://github.com/MaazAli/Meteor-HighCharts/tree/master/lib) and reference it in [package.js](https://github.com/MaazAli/Meteor-HighCharts/blob/master/package.js)

**Comment by mhourahine** [comment]
Thanks. That worked. Are you interested in including it in your package?  If so, I'll submit a pull request.

**Comment by jhuenges** [comment]
I guess it would be a nice addition. @MaazAli ?

**Comment by MaazAli** [comment]
I agree. I'm currently looking over the pull request.
