### ISSUE TITLE
Move highcharts-more and highcharts-solid-gauge into separate packages?

### ISSUE THREAD

**Issue by MaazAli** [MaazAli/Meteor-HighCharts#12]
Why don't we move these into separate packages that just require this package as a dependency. That way we can ensure that users that only want the core of highcharts are able to get it without adding any extra functionality that they don't need. @jhuenges thoughts?

**Comment by jhuenges** [comment]
Yep, sounds good

**Comment by jhuenges** [comment]
I guess this can be closed
