### ISSUE TITLE
How to show no data message?

### ISSUE THREAD

**Issue by javaknight** [MaazAli/Meteor-HighCharts#20]
The library mentions including a no-data JS file - how can we do this in Meteor?

**Comment by jhuenges** [comment]
Can you post a link to where the library mentions that?

**Comment by javaknight** [comment]
http://api.highcharts.com/highcharts#noData

**Comment by jhuenges** [comment]
I ll take a look at it!

**Comment by jhuenges** [comment]
I opened #22 which adds this feature. @MaazAli needs to take another look at it an merge it (and publish it)
