### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by janka** [MaazAli/Meteor-HighCharts#28]
Hi

What is the ETA of 0.4.0? I'm eagerly waiting for reactive charts :-)

Jan

**Comment by jhuenges** [comment]
What feature are you currently missing?

**Comment by janka** [comment]
Only what seems to be in master, with version number and all. Just wondering if I should clone or just wait a day or two for it.
"meteor add" gives me 0.3.0, in master there's 0.4.0 with the "realtime charts" commit.

**Comment by jhuenges** [comment]
Oh, yeah. You are right. Lets call @MaazAli

**Comment by MaazAli** [comment]
Pushed the latest onto atmosphere!

**Comment by janka** [comment]
Thanks!
