### ISSUE TITLE
HighCharts

### ISSUE THREAD

**Issue by xcrypto** [MaazAli/Meteor-HighCharts#30]
Hi MaazAli,

How are you?  This is not an issue, but a request - would it be possible to include other modules in your Meteor HighCharts package (e.g., exporting, drilldown, no-data-to-display, etc.)   

Thanks.

**Comment by jhuenges** [comment]
No-data-to display should work (#22)

**Comment by xcrypto** [comment]
Hi - thanks for the update.  What about exporting?

**Comment by jhuenges** [comment]
Exporting is not possible right now. There are two options:
a) make exporting part of the 'main' package (this)
b) make an additional exporting package and let the user decide if he wants to use it

**Comment by xcrypto** [comment]
Ok.  I understand.  Either option is good, though B) is best perhaps in 
that it allow the choice.  However, on the other hand, if one chooses to 
integrate HighCharts, the key features of 3D, exporting, and drilldown 
would be useful - I think.

Which is easiest for you --  Option A or Option B?

Is this something that can be done quickly?

Thanks.

**Comment by jhuenges** [comment]
Drilldowns and 3D are available through [separate packages](https://github.com/MaazAli/Meteor-HighCharts/blob/master/readme.md#more-charts)

**Comment by xcrypto** [comment]
Got it...thanks.
