### ISSUE TITLE
Destroy and Re-draw

### ISSUE THREAD

**Issue by chasemb** [MaazAli/Meteor-HighCharts#31]
I can't seem to find a way to chartObject.destroy() and redraw the chart.  Please advise.  Thanks!

**Comment by jhuenges** [comment]
Whats the use case?

**Comment by chasemb** [comment]
Changing data or date ranges, etc.

**Comment by jhuenges** [comment]
Is the data based on a collection?

Otherwise: http://api.highcharts.com/highcharts#Chart.redraw

**Comment by chasemb** [comment]
Yeah, based on query from db.  Where do i have access to the chart object to manipulate?

**Comment by jhuenges** [comment]
Have you looked at the examples? There is a way to connect the collection directly to the chart. Give me a moment and I ll try to find a better answer :P If you want to, you can show me some code.

**Comment by chasemb** [comment]
Shoot me in the face.  Didn't see the demos and didn't realize the highcharts library was exposed.  I was using the helper...  Sorry for your time.

**Comment by jhuenges** [comment]
No shooting today ;) 
You can take a look at: http://meteorpad.com/pad/i96DNwX9H6pr959oL/Highcharts%20#2
I wrote this some time ago, but it has a nice solution on how to update the data (maybe even better than the demos :P )

**Comment by Hareramrai** [comment]
Can someone help me redraw the graph with new data ? 
I am not getting documentation for the same. 

Thank you.

**Comment by jhuenges** [comment]
Have you tried one of the examples here: https://github.com/jhuenges/highcharts-demo ?
