### ISSUE TITLE
StockCharts

### ISSUE THREAD

**Issue by levino** [MaazAli/Meteor-HighCharts#8]
Can one use stockcharts with this package? Would be much appreciated.

Cheers

Levin

**Comment by Levino** [comment]
@jhuenges Happy new year. Did you start on some work related to this? :)

**Comment by jhuenges** [comment]
@Levino Thanks and happy new year!
I managed to throw something together: https://atmospherejs.com/jhuenges/highstock
Please tell me if there is something wrong. I havent tested it with data from a collection, but i guess it should worl ;)
